[APP_CONFIG]

# To the front of the UI
[APP_CONFIG.highlighted]
modules=[
    "reporting_module"
]

# Hidden in a menu
[APP_CONFIG.hidden]
modules=[
    "chat",
    "generate_charts"
]


[TABLE_TIMES]
# Vente
sale_order="date_order"
# valeurs possibles: date_order | sale_order_create_date | sale_order_write_date

# Achat
purchase_order="date_order"
# valeurs possibles: date_order | purchase_order_create_date | purchase_order_write_date
